# Generated by Django 2.1 on 2021-03-16 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_video_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='likes',
        ),
    ]
