# Generated by Django 2.1 on 2021-03-16 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0006_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='status',
            new_name='gender',
        ),
    ]
